# Generated by Django 4.2.15 on 2025-02-11 15:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CollegeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('cfms_id', models.CharField(max_length=50)),
                ('salutation', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], default='Choose', max_length=15, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='media/staff_pics/')),
                ('staff_type', models.CharField(choices=[('Teaching', 'Teaching'), ('Non Teaching', 'Non Teaching')], default='Choose', max_length=20)),
                ('mobile_no', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Mobile number must be 10 digits.', regex='^[0-9]{10}$')])),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('doj_in_govt_service', models.DateField(null=True)),
                ('doj_in_college', models.DateField()),
                ('date_of_exite', models.DateField(default=None, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('is_hod', models.BooleanField(default=False)),
                ('aadhar_number', models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Aadhar number must be 12 digits.', regex='^[0-9]{12}$')])),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Transferred', 'Transferred'), ('Departed', 'Departed')], default='Choose', max_length=20)),
                ('salary', models.CharField(max_length=8, null=True)),
                ('previous_working_station', models.CharField(max_length=100, null=True)),
                ('transferred_college_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CollegeApp.address')),
                ('bank', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CollegeApp.bank_details')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.college')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CollegeApp.department')),
            ],
        ),
    ]
