# Generated by Django 4.2.15 on 2025-02-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminemail', models.CharField(max_length=50)),
                ('adminpassword', models.CharField(max_length=50)),
            ],
        ),
    ]
