# Generated by Django 4.2.15 on 2025-02-11 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('doorNo', models.CharField(max_length=10, null=True)),
                ('village', models.CharField(max_length=300, null=True)),
                ('street', models.CharField(max_length=30, null=True)),
                ('mandal', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('pin_code', models.CharField(max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bank_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medium', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_short_name', models.CharField(max_length=10)),
                ('program_full_name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'unique_together': {('program_short_name',)},
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.state')),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_code', models.CharField(max_length=6, unique=True)),
                ('college_name', models.CharField(max_length=100, null=True)),
                ('college_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone_no', models.CharField(max_length=10, null=True, unique=True)),
                ('status', models.CharField(default='pending', max_length=6)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CollegeApp.address')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bank_details',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_account_num', models.CharField(max_length=20, null=True)),
                ('ifsc_code', models.CharField(max_length=20, null=True)),
                ('branch_name', models.CharField(max_length=100, null=True)),
                ('bank_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.bank_name')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.district'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.state'),
        ),
        migrations.CreateModel(
            name='SubjectCombination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('combination_short_form', models.CharField(max_length=10, unique=True)),
                ('combination_full_form', models.CharField(default=None, max_length=50)),
                ('program', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='CollegeApp.program')),
            ],
            options={
                'unique_together': {('combination_short_form',)},
            },
        ),
    ]
