# Generated by Django 4.2.15 on 2025-03-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='program',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subjectcombination',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='college',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
