# Generated by Django 4.2.15 on 2025-02-11 15:37

import CollegeApp.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('CollegeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('father_aadhar', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(code='invalid_aadhar', message='Aadhar number must be 12 digits.', regex='^[0-9]{12}$')])),
                ('mother_aadhar', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(code='invalid_aadhar', message='Aadhar number must be 12 digits.', regex='^[0-9]{12}$')])),
                ('mobile', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Mobile number must be 10 digits.', regex='^[0-9]{10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OAMDC_NO', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('pic', models.ImageField(blank=True, upload_to='media/student_pics/')),
                ('mobile_no', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Mobile number must be 10 digits.', regex='^[0-9]{10}$')])),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=15)),
                ('date_of_birth', models.DateField(null=True)),
                ('mother_tongue', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Telugu', 'Telugu'), ('Tamil', 'Tamil'), ('Kannada', 'Kannada'), ('Malayalam', 'Malayalam'), ('Marathi', 'Marathi'), ('Bengali', 'Bengali'), ('Gujarati', 'Gujarati'), ('Punjabi', 'Punjabi'), ('Urdu', 'Urdu')], max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=10, null=True)),
                ('place_of_birth', models.CharField(max_length=100, null=True)),
                ('ssc_hall_ticket', models.CharField(blank=True, max_length=20, null=True)),
                ('ssc_school_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ssc_year_of_study', models.IntegerField(blank=True, null=True, validators=[CollegeApp.models.validate_year])),
                ('ssc_marks', models.CharField(blank=True, max_length=6, null=True)),
                ('ssc_marks_file', models.FileField(blank=True, null=True, upload_to='media/ssc_marks_file/')),
                ('intermediate_hall_ticket_no', models.CharField(blank=True, max_length=20, null=True)),
                ('intermediate_college_name', models.CharField(blank=True, max_length=100, null=True)),
                ('intermediate_year_of_study', models.IntegerField(blank=True, null=True, validators=[CollegeApp.models.validate_year])),
                ('intermediate_marks', models.CharField(blank=True, max_length=6, null=True)),
                ('intermediate_marks_file', models.FileField(blank=True, null=True, upload_to='media/intermediate_marks_file/')),
                ('caste', models.CharField(blank=True, max_length=50, null=True)),
                ('caste_certificate_no', models.CharField(blank=True, max_length=20, null=True)),
                ('caste_certificate_file', models.FileField(blank=True, null=True, upload_to='media/caste_certificates_file/')),
                ('income_certificate_no', models.CharField(blank=True, max_length=20, null=True)),
                ('income_certificate_file', models.FileField(blank=True, null=True, upload_to='media/income_certificates_file/')),
                ('aadhar_no', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_aadhar', message='Aadhar number must be 12 digits.', regex='^[0-9]{12}$')])),
                ('aadhar_file', models.FileField(blank=True, null=True, upload_to='media/aadhar_files/')),
                ('year_of_admission', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('OnGoing', 'OnGoing'), ('Graduate', 'Graduate'), ('DropOut', 'DropOut')], max_length=20)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CollegeApp.address')),
                ('bank', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CollegeApp.bank_details')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.college')),
                ('medium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CollegeApp.medium')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='staff.staff')),
                ('parent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.parent')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CollegeApp.program')),
                ('subject_combination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CollegeApp.subjectcombination')),
            ],
        ),
    ]
